// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/api/ml_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       int32                  `protobuf:"varint,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelChunk) Reset() {
	*x = ModelChunk{}
	mi := &file_internal_api_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelChunk) ProtoMessage() {}

func (x *ModelChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelChunk.ProtoReflect.Descriptor instead.
func (*ModelChunk) Descriptor() ([]byte, []int) {
	return file_internal_api_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *ModelChunk) GetChunkId() int32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ModelChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GradientChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradientChunk) Reset() {
	*x = GradientChunk{}
	mi := &file_internal_api_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradientChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradientChunk) ProtoMessage() {}

func (x *GradientChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradientChunk.ProtoReflect.Descriptor instead.
func (*GradientChunk) Descriptor() ([]byte, []int) {
	return file_internal_api_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *GradientChunk) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GradientChunk) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GradientChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_api_ml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_api_ml_service_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRequest) Reset() {
	*x = ModelRequest{}
	mi := &file_internal_api_ml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRequest) ProtoMessage() {}

func (x *ModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRequest.ProtoReflect.Descriptor instead.
func (*ModelRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_ml_service_proto_rawDescGZIP(), []int{3}
}

var File_internal_api_ml_service_proto protoreflect.FileDescriptor

const file_internal_api_ml_service_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/api/ml_service.proto\x12\x03api\";\n" +
	"\n" +
	"ModelChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\x05R\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"W\n" +
	"\rGradientChunk\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0e\n" +
	"\fModelRequest2t\n" +
	"\x0fMLWorkerService\x120\n" +
	"\bGetModel\x12\x11.api.ModelRequest\x1a\x0f.api.ModelChunk0\x01\x12/\n" +
	"\rSendGradients\x12\x12.api.GradientChunk\x1a\b.api.Ack(\x01B3Z1github.com/yourusername/raft-ml-grid/internal/apib\x06proto3"

var (
	file_internal_api_ml_service_proto_rawDescOnce sync.Once
	file_internal_api_ml_service_proto_rawDescData []byte
)

func file_internal_api_ml_service_proto_rawDescGZIP() []byte {
	file_internal_api_ml_service_proto_rawDescOnce.Do(func() {
		file_internal_api_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_ml_service_proto_rawDesc), len(file_internal_api_ml_service_proto_rawDesc)))
	})
	return file_internal_api_ml_service_proto_rawDescData
}

var file_internal_api_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_api_ml_service_proto_goTypes = []any{
	(*ModelChunk)(nil),    // 0: api.ModelChunk
	(*GradientChunk)(nil), // 1: api.GradientChunk
	(*Ack)(nil),           // 2: api.Ack
	(*ModelRequest)(nil),  // 3: api.ModelRequest
}
var file_internal_api_ml_service_proto_depIdxs = []int32{
	3, // 0: api.MLWorkerService.GetModel:input_type -> api.ModelRequest
	1, // 1: api.MLWorkerService.SendGradients:input_type -> api.GradientChunk
	0, // 2: api.MLWorkerService.GetModel:output_type -> api.ModelChunk
	2, // 3: api.MLWorkerService.SendGradients:output_type -> api.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_ml_service_proto_init() }
func file_internal_api_ml_service_proto_init() {
	if File_internal_api_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_ml_service_proto_rawDesc), len(file_internal_api_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_ml_service_proto_goTypes,
		DependencyIndexes: file_internal_api_ml_service_proto_depIdxs,
		MessageInfos:      file_internal_api_ml_service_proto_msgTypes,
	}.Build()
	File_internal_api_ml_service_proto = out.File
	file_internal_api_ml_service_proto_goTypes = nil
	file_internal_api_ml_service_proto_depIdxs = nil
}
