// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: internal/api/ml_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLWorkerService_GetModel_FullMethodName      = "/api.MLWorkerService/GetModel"
	MLWorkerService_SendGradients_FullMethodName = "/api.MLWorkerService/SendGradients"
)

// MLWorkerServiceClient is the client API for MLWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLWorkerServiceClient interface {
	GetModel(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ModelChunk], error)
	SendGradients(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GradientChunk, Ack], error)
}

type mLWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLWorkerServiceClient(cc grpc.ClientConnInterface) MLWorkerServiceClient {
	return &mLWorkerServiceClient{cc}
}

func (c *mLWorkerServiceClient) GetModel(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ModelChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MLWorkerService_ServiceDesc.Streams[0], MLWorkerService_GetModel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ModelRequest, ModelChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLWorkerService_GetModelClient = grpc.ServerStreamingClient[ModelChunk]

func (c *mLWorkerServiceClient) SendGradients(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GradientChunk, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MLWorkerService_ServiceDesc.Streams[1], MLWorkerService_SendGradients_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GradientChunk, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLWorkerService_SendGradientsClient = grpc.ClientStreamingClient[GradientChunk, Ack]

// MLWorkerServiceServer is the server API for MLWorkerService service.
// All implementations must embed UnimplementedMLWorkerServiceServer
// for forward compatibility.
type MLWorkerServiceServer interface {
	GetModel(*ModelRequest, grpc.ServerStreamingServer[ModelChunk]) error
	SendGradients(grpc.ClientStreamingServer[GradientChunk, Ack]) error
	mustEmbedUnimplementedMLWorkerServiceServer()
}

// UnimplementedMLWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLWorkerServiceServer struct{}

func (UnimplementedMLWorkerServiceServer) GetModel(*ModelRequest, grpc.ServerStreamingServer[ModelChunk]) error {
	return status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedMLWorkerServiceServer) SendGradients(grpc.ClientStreamingServer[GradientChunk, Ack]) error {
	return status.Error(codes.Unimplemented, "method SendGradients not implemented")
}
func (UnimplementedMLWorkerServiceServer) mustEmbedUnimplementedMLWorkerServiceServer() {}
func (UnimplementedMLWorkerServiceServer) testEmbeddedByValue()                         {}

// UnsafeMLWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLWorkerServiceServer will
// result in compilation errors.
type UnsafeMLWorkerServiceServer interface {
	mustEmbedUnimplementedMLWorkerServiceServer()
}

func RegisterMLWorkerServiceServer(s grpc.ServiceRegistrar, srv MLWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedMLWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLWorkerService_ServiceDesc, srv)
}

func _MLWorkerService_GetModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ModelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MLWorkerServiceServer).GetModel(m, &grpc.GenericServerStream[ModelRequest, ModelChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLWorkerService_GetModelServer = grpc.ServerStreamingServer[ModelChunk]

func _MLWorkerService_SendGradients_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MLWorkerServiceServer).SendGradients(&grpc.GenericServerStream[GradientChunk, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLWorkerService_SendGradientsServer = grpc.ClientStreamingServer[GradientChunk, Ack]

// MLWorkerService_ServiceDesc is the grpc.ServiceDesc for MLWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.MLWorkerService",
	HandlerType: (*MLWorkerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetModel",
			Handler:       _MLWorkerService_GetModel_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendGradients",
			Handler:       _MLWorkerService_SendGradients_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/api/ml_service.proto",
}
